"use strict";
let placeTOVisit = ["Pakistan", "China", "saudi arab", "london", "iran"];
// console.log(placeToVisite);
// console.log(placeToVisite.shot());
// console.log(placeToVisit);
// console.log(placeToVisit.shot().reverse());
// console.log(placeTOVisit);
// console.log(placeToVisite.reverse());
// console.log (placeToVisit.reversr());
let sortedArray = ["Pakistan", "China", "saudi arab", "london", "iran"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
